<?php
/** @var \Bluz\Layout\Layout $this */

use Bluz\Proxy\Layout;
use Bluz\Proxy\Messages;

?>
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?=Layout::title()?></title>
    <base href="<?=$this->baseUrl()?>" />
    <link rel="profile" href="http://gmpg.org/xfn/11"/>
    <link rel="stylesheet" href="<?=$this->baseUrl('css/bootstrap.css')?>" />
    <link rel="stylesheet" href="<?=$this->baseUrl('gourmet/css/slider.css')?>" />
    <link rel="stylesheet" href="<?=$this->baseUrl('gourmet/css/style.css')?>" />
    <link rel="stylesheet" href="<?=$this->baseUrl('css/print.css')?>" media="print" />


    <link rel="apple-touch-icon" sizes="152x152" href="<?=$this->baseUrl('img/apple-touch-icon-152x152.png')?>" />
    <link rel="apple-touch-icon" sizes="180x180" href="<?=$this->baseUrl('img/apple-touch-icon-180x180.png')?>" />
    <link rel="icon" type="image/png" href="<?=$this->baseUrl('img/favicon-16x16.png')?>" sizes="16x16" />
    <link rel="icon" type="image/png" href="<?=$this->baseUrl('img/favicon-32x32.png')?>" sizes="32x32" />
    <link rel="icon" type="image/png" href="<?=$this->baseUrl('img/favicon-96x96.png')?>" sizes="96x96" />
    <link rel="icon" type="image/png" href="<?=$this->baseUrl('img/android-chrome-192x192.png')?>" sizes="192x192" />
    <link rel="manifest" href="<?=$this->baseUrl('img/manifest.json')?>" />
    <link rel="shortcut icon" href="<?=$this->baseUrl('img/favicon.ico')?>" />
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<?=$this->baseUrl('img/mstile-144x144.png')?>" />
    <meta name="msapplication-config" content="<?=$this->baseUrl('img/browserconfig.xml')?>" />
    <meta name="theme-color" content="#ffffff" />

    <script src="<?=$this->baseUrl('js/vendor/require.min.js')?>"></script>
<!--    <script src="--><?//=$this->baseUrl('js/config.js')?><!--"></script>-->
    <script src="<?=$this->baseUrl('gourmet/js/jquery.js')?>"></script>
    <script src="<?=$this->baseUrl('gourmet/js/jquery-migrate-1.1.1.js')?>"></script>
    <script src="<?=$this->baseUrl('gourmet/js/superfish.js')?>"></script>
    <script src="<?=$this->baseUrl('gourmet/js/jquery.easing.1.3.js')?>"></script>
    <script src="<?=$this->baseUrl('gourmet/js/sForm.js')?>"></script>
    <script src="<?=$this->baseUrl('gourmet/js/jquery.carouFredSel-6.1.0-packed.js')?>"></script>
    <script src="<?=$this->baseUrl('gourmet/js/tms-0.4.1.js')?>"></script>

    <script>
        $(window).load(function () {
            $('.slider')._TMS({
                show: 0,
                pauseOnHover: false,
                prevBu: '.prev',
                nextBu: '.next',
                playBu: false,
                duration: 800,
                preset: 'fade',
                pagination: true, //'.pagination',true,'<ul></ul>'
                pagNums: false,
                slideshow: 8000,
                numStatus: false,
                banners: false,
                waitBannerAnimation: false,
                progressBar: false
            })
        });
        $(window).load(function () {
            $('.carousel1').carouFredSel({
                auto: false,
                prev: '.prev',
                next: '.next',
                width: 960,
                items: {
                    visible: {
                        min: 1,
                        max: 4
                    },
                    height: 'auto',
                    width: 240,
                },
                responsive: false,
                scroll: 1,
                mousewheel: false,
                swipe: {
                    onMouse: false,
                    onTouch: false
                }
            });
        });
    </script>


    <!-- For IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="<?=$this->baseUrl('/js/vendor/html5shiv.js')?>"></script>
    <script src="<?=$this->baseUrl('/js/vendor/html5shiv-printshiv.js')?>"></script>
    <![endif]-->

    <?=Layout::headScript();?>
    <?=Layout::headStyle();?>
    <?=Layout::link();?>
    <?=Layout::meta();?>
</head>
<body data-spy="scroll" data-bluz-module="<?=$this->module()?>" data-bluz-controller="<?=$this->controller()?>">
<?php if (Messages::count()):
    // JS not allow read headers of current request, only for XMLHTTPRequests :(
    ?>
    <script>
        require(['bluz.notify'], function(notify) {
            notify.set(<?=json_encode(Messages::popAll())?>);
        });
    </script>
<?php endif; ?>
