<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */
if (!$grid) return;
?>
<script>
    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.grid']);
</script>

<div class="clearfix" data-spy="grid" data-grid="<?=$grid->getUid()?>">
    <nav class="navbar navbar-default" role="navigation">

    <form method="post" action="<?= $this->url('menu', 'grid')?>">
        <?php foreach($menu as $row) : ?>
        <div class="col-lg-12">
            <div class="col-lg-1"><label><?= $row->id ?></label></div>
            <div class="col-lg-6">
                <select class="form-control" id="shelf<?= $row->id ?>" name="shelf<?= $row->id ?>">
                    <?php foreach ($dishes as $dish): ?>
                        <option
                            <?php if ($dish->name == $row->name) echo 'selected' ?>
                        value="<?= $dish->id ?>"><?= $dish->name ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <?php endforeach; ?>
        <div class="modal-footer" >
            <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>
        </div>
    </form>

</div>
