<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<?php $uid = uniqid('form_'); ?>
<form id="<?=$uid?>" action="<?=$this->url('dishes', 'crud')?>" class="form-horizontal ajax" method="<?=$method?>">
    <input type="hidden" name="id" value="<?=($row->id) ?: 0?>"/>
    <input type="hidden" name="_method" value="<?=$method?>"/>
    <div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><?=__('Edit page')?></h4>
    </div>
    <div class="modal-body">
        <div class="form-group">
            <label class="control-label col-lg-2" for="name"><?=__('Name')?>:</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="name" name="name" value="<?=esc($row->name)?>" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-12">
                <label for="description" class="control-label"><?=__('Description')?>:</label>
                <textarea rows="24" cols="26" id="description" class="form-control redactor" name="description" ><?=esc(($row->description) ?: '')?></textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2" for="price"><?=__('Price')?>:</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" id="price" name="price" value="<?=esc($row->price)?>" />
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
        <a href="#" class="btn btn-default" data-dismiss="modal"><?=__('Close')?></a>
    </div>
    </div>
</form>
<?= $this->redactor('.redactor', ['minHeight' => 480]) ?>
<script>
    require(['jquery', 'bluz.tools'], function($, tools) {
        $("#title").blur(function() {
            var $alias = $("#alias");
            if ($alias.val() == "") {
                var title = $(this).val();
                title = tools.alias(title);
                $alias.val(title);
            }
        });
    });
</script>
<?php
// need for plain request
if (isset($errors)) :
    $data = json_encode(['errors'=>$errors]);
    $this->headScript('require(["bluz.form"], function(form) {
        form.notices($("#'.$uid.'"), '.$data.');
    });');
endif;
?>