<?php
/**
 * Created by PhpStorm.
 * User: valeriy
 * Date: 08.12.16
 * Time: 18:13
 */

if (!$grid) return;
?>
<script>
    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.grid']);
</script>

<div class="clearfix" data-spy="grid" data-grid="<?=$grid->getUid()?>">
    <nav class="navbar navbar-default" role="navigation">
        <div class="col-lg-6">
            <a href="<?=$this->url('dishes', 'crud')?>" class="btn btn-primary navbar-btn dialog" data-ajax-method="get" data-modal-style="width:800px"><?=__('Create')?></a>
        </div>
        <div class="col-lg-6">
            <form action="<?=$this->url('dishes', 'grid')?>" class="navbar-form filter-form pull-right">
                <div class="input-group">
                    <?php echo ''
                    //                    $this->partial(
                    //                        'grid/filter-search.phtml',
                    //                        [
                    //                            'grid' => $grid,
                    //                            'filters' => [
                    //                                'title' => __('Title'),
                    //                                'alias' => __('Alias'),
                    //                                'description' => __('Description'),
                    //                                'content' => __('Content'),
                    //                            ]
                    //                        ]
                    //                    )
                    ?>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><?=__("Search")?></button>
                    </span>
                </div>
            </form>
        </div>
    </nav>

    <?=$this->partial('grid/total.phtml', ['grid'=>$grid]) ?>
    <?=$this->partial('grid/limit.phtml', ['grid'=>$grid]) ?>

    <table class="table table-hover table-striped grid">
        <thead>
        <tr>
            <th width="40px"><?=__('Id')?></th>
            <th><?=__('email')?></th>

            <th width="72px"></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($grid->getData() as $row) : ?>
            <tr>
                <td><?=$row['id']?></td>
                <td><?=esc($row['email'])?></td>
                <td class="controls">
                    <a href="<?=$this->url('dishes', 'crud', ['id' => $row['id']])?>" class="confirm btn btn-xs btn-danger ajax" data-ajax-method="delete">
                        <i class="fa fa-trash-o"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?=$this->partial('grid/empty-rows.phtml', ['grid'=>$grid]) ?>
    <?=$this->partial('grid/pagination.phtml', ['grid'=>$grid]) ?>
    <?=$this->partial('grid/total.phtml', ['grid'=>$grid]) ?>

</div>
