<body>
<div class="main">
    <header>
        <div class="dashboard-link"><?=$this->ahref('Dashboard', ['dashboard', 'index'])?></div>

        <div class="container_12">
            <div class="grid_12">
                <h1><a href="#"><img src="images/fransua.png" alt=""></a></h1>
                <div class="menu_block">
                    <nav>
                        <ul class="sf-menu">
                            <li><a href="#work-time"><?= __('Режим работы') ?></a></li>
                            <li><a href="#salad-menu"><?= __('Меню') ?></a></li>
                            <li><a href="#send-commit"><?= __('Оставить отзыв') ?></a></li>
                            <!--                            <li><a href="#">--><?//= __('Отзывы') ?><!--</a></li>-->
                        </ul>
                    </nav>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </header>
    <div class="slider-relative">
        <div class="slider-block">
            <div class="slider">
                <ul class="items">
                    <li><img src="images/slide.jpg" alt=""></li>
                    <li><img src="images/slide1.jpg" alt=""></li>
                    <li class="mb0"><img src="images/slide2.jpg" alt=""></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="content page1">
        <div class="container_12">
            <div class="grid_7">
                <h2 id="work-time"><?= __('Режим работы') ?></h2>

                <div class="extra_wrapper">
                    <p>Автомат работает круглосуточно </p>
                    Обновление блюд с 8:00 до 9:00 в будние дни <br>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="clear"></div>
            <div class="grid_12">
                <div class="hor_separator"></div>
            </div>
            <div class="grid_12">
                <div class="car_wrap">
                    <h2 id="salad-menu"><?= __('Сегодня мы предлогаем')?></h2>
                    <!--                    <a href="#" class="prev"></a><a href="#" class="next"></a>-->
                    <ul class="carousel1">
                        <?php $number = 4;
                        $list = [];
                        $count = count($menu);
                        $order = 1;
                        foreach ($menu as $dish):
                        if (in_array($dish->name, $list)) continue;
                            ?>
                        <li>
                            <div><img src="images/page1_img1.jpg" alt="">
                                <div class="col1 upp"> <a href="#"><?= $dish->name ?></a></div>
                                <p><span> <?= $dish->description ?></span></p>
                                <div class="price"><?= $dish->price / 100 ?> грн</div>
                            </div>
                        </li>
                        <?php
                        if ($order % $number == 0 && $order != $count): ?>
                            </ul>
                            <div class="hor_separator"></div>
                            <ul class="carousel1">

                        <?php
                        endif;
                        $order += 1;
                        $list[] = $dish->name;
                        endforeach;

                        ?>
                    </ul>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="container_12">
        <div class="hor_separator"></div>
        <div class="grid_6">
            <h3 id="send-commit"><?= __('Оставить отзыв')?></h3>
            <p class="col1">Тут Вы можете оставить отзыв или написать что бы Вы хотели видеть в меню</p>
            <form id="recall-info" action="#">
                <label >
                    <textarea id="textarea-commit" class="form-control" rows="3" placeholder="Отзыв"></textarea>
                    <a id="send-commit-btn" href="#send-commit" class="btn" data-type="submit"><?= __('Отправить отзыв') ?></a></label>
            </form>
        </div>
        <div class="grid_6">
            <h3><?= __('Подписаться на рассылку')?></h3>
            <p class="col1">Вы можете подписаться на нашу рассылку для получения информации об изменении меню или режима работы</p>
            <form id="newsletter" action="#">
                <div class="success">Your subscribe request has been sent!</div>
                <label class="email">
                    <input type="email" value="" placeholder="Email">
                    <a href="#" class="btn" data-type="submit"><?= __('Подписаться') ?></a> <span class="error">*This is not a valid email address.</span> </label>
            </form>
        </div>
    </div>

    <div class="container_12">
        <div class="hor_separator"></div>
    </div>
</div>

</body>